language: objective-c
script:
  - xcodebuild -project MCSNotificationController.xcodeproj -scheme MCSNotificationController-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project MCSNotificationController.xcodeproj -scheme MCSNotificationController-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -project MCSNotificationController.xcodeproj -scheme MCSNotificationController-Mac ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project MCSNotificationController.xcodeproj -scheme MCSNotificationController-Mac ONLY_ACTIVE_ARCH=NO

